# file: locators.py
from config import *
import uiautomator2 as u2

d = u2.connect(device_id)


class MainLocators:
    # BASE
    X_BUTTON = '//android.widget.ImageButton'
    NOTIFICATION_NEGATIVE = '//*[@resource-id="ru.limeshop.android.dev:id/notification_negative_button"]'
    TOOLBAR_TITLE = 'ru.limeshop.android.dev:id/toolbarTitle'
    lime_logo = 'ru.limeshop.android.dev:id/banner_label_image_view'

    # NAV_BAR
    SEARCH_NAV = 'ru.limeshop.android.dev:id/nav_search'
    FAVORITES_NAV = 'ru.limeshop.android.dev:id/nav_favorites'
    CATALOG_NAV = 'ru.limeshop.android.dev:id/nav_catalog_menu'
    PROFILE_NAV = 'ru.limeshop.android.dev:id/nav_profile'
    CART_NAV = 'ru.limeshop.android.dev:id/nav_cart'

    # CATALOG
    MENU_ITEM_1 = f'//*[@text="{menu_l1}"]'
    MENU_ITEM_2 = f'//*[@text="{menu_l2}"]'
    FAV_ICON = 'ru.limeshop.android.dev:id/favoriteImageView'
    NAME_PRODUCT_COLLECTION = 'ru.limeshop.android.dev:id/nameTextView'
    NAME_PRODUCT_FAVORITE = 'ru.limeshop.android.dev:id/item_product_name'
    FILTER_BUTTON = '//*[@resource-id="ru.limeshop.android.dev:id/filter_menu"]'
    PRODUCT_CARD_1_1 = '//*[@resource-id="ru.limeshop.android.dev:id/recycler_catalog"]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.FrameLayout[1]'
    PRODUCT_CARD_2_2 = '//*[@resource-id="ru.limeshop.android.dev:id/recycler_catalog"]/android.widget.FrameLayout[2]/android.view.ViewGroup[1]'
    PRODUCT_CARD_1 = '//android.widget.TableLayout/android.widget.TableRow[1]/android.view.ViewGroup[1]/android.widget.FrameLayout[1]'
    PRODUCT_CARD_2 = '//android.widget.TableLayout/android.widget.TableRow[2]/android.view.ViewGroup[2]/android.widget.FrameLayout[1]'

    registration_btn = 'ru.limeshop.android.dev:id/profile_unauthorized_signup'
    name = '//*[@text="Имя"]'
    surname = '//*[@text="Фамилия"]'
    phone = '//*[@text="Моб. телефон"]'
    email = '//*[@text="Эл. почта"]'
    password = '//*[@text="Пароль"]'
    repeat_password = '//*[@text="Повтор нового пароля"]'
    approve_checkbox = 'ru.limeshop.android.dev:id/checkable_option_active'
    continue_btn = '//*[@text="ПРОДОЛЖИТЬ"]'
    submenu_elements_list = d(resourceId='ru.limeshop.android.dev:id/catalog_item_recycler').child(
        resourceId="ru.limeshop.android.dev:id/catalog_item_name")

class SearchLocators:
    X_BUTTON = '//android.widget.ImageButton'
    TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/toolbarTitle"]'
    TEXT_EDIT = '//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    TEXT_HINT = '//*[@resource-id="ru.limeshop.android.dev:id/hintText"]'
    ICON = '//*[@resource-id="ru.limeshop.android.dev:id/startIcon"]'
    SHOPS_BTN = '//*[@resource-id="ru.limeshop.android.dev:id/topButtonsContainerLinearLayout"]/androidx.appcompat.widget.LinearLayoutCompat[1]'
    SCAN_BTH = '//*[@resource-id="ru.limeshop.android.dev:id/topButtonsContainerLinearLayout"]/androidx.appcompat.widget.LinearLayoutCompat[2]'
    SHOPS_TEXT = '//*[@text="МАГАЗИНЫ"]'
    SCAN_TEXT = '//*[@text="СКАНЕР"]'
    ALL = '//*[@text="ВСЕ"]'
    WOMAN = '//*[@text="ЖЕНЩИНЫ"]'
    MEN = '//*[@text="МУЖЧИНЫ"]'
    KIDS = '//*[@text="ДЕТИ"]'
    FIRST_RESULT_IMAGE = '//*[@resource-id="ru.limeshop.android.dev:id/searchRecyclerView"]/android.view.ViewGroup[1]/android.widget.FrameLayout[1]'
    FIRST_RESULT_NAME = '"ru.limeshop.android.dev:id/item_product_name", text="ПЛАТЬЕ ИЗ АТЛАСА С ПРИНТОМ «ЖЕМЧУГ»"'
    FIRST_RESULT_FAV = '//*[@resource-id="ru.limeshop.android.dev:id/searchRecyclerView"]/android.view.ViewGroup[1]/android.widget.ImageView[1]'
    ICON_FAIL_SEARCH = '//androidx.appcompat.widget.LinearLayoutCompat/android.widget.ImageView[1]'
    FAIL_SEARCH_TEXT = '//*[@text="НИЧЕГО НЕ НАЙДЕНО"]'
    FAIL_SEARCH_DESCRIPTION = '//*[@text="Проверьте, правильно ли введен запрос"]'

class CatalogLocators:
    WOMEN = '//*[@text="ЖЕНЩИНЫ"]'
    MEN = '//*[@text="МУЖЧИНЫ"]'
    KIDS = '//*[@text="ДЕТИ"]'
    EDITORIAL = '//*[@text="EDITORIAL"]'
    GIFT_CARD = '//*[@text="ПОДАРОЧНАЯ КАРТА"]'
    MENU_ITEM = "ru.limeshop.android.dev:id/catalog_item_name"
    catalog_item = 'ru.limeshop.android.dev:id/catalog_item_name'
    catalog_item_recycler = 'ru.limeshop.android.dev:id/catalog_item_recycler'
    submenu_elements_list = '//*[@resource-id="ru.limeshop.android.dev:id/catalog_item_recycler"]//*[@resource-id="ru.limeshop.android.dev:id/catalog_item_name"]'
    cards_image = 'ru.limeshop.android.dev:id/media_view_container_layout'


class ProductCardLocators:
    # PRODUCT_CARD
    BUY = '//*[@resource-id="ru.limeshop.android.dev:id/buy_button"]'
    BUY_MORE = '//*[@resource-id="ru.limeshop.android.dev:id/buy_more_button"]'
    COLORS = '//*[@resource-id="ru.limeshop.android.dev:id/productColorsConstraintLayout"]'
    FAVORITE = '//*[@resource-id="ru.limeshop.android.dev:id/productAddToFavoritesImageButton"]'
    SHARE = '//*[@resource-id="ru.limeshop.android.dev:id/productShareImageButton"]'
    CART = '//*[@resource-id="ru.limeshop.android.dev:id/productCartImageButton"]'
    PHOTO_ZOOM = '//*[@resource-id="ru.limeshop.android.dev:id/productPhotosViewpager"]'
    ART = '//*[@resource-id="ru.limeshop.android.dev:id/productArticleTextView"]'
    SIZES_GUIDE = '//*[@resource-id="ru.limeshop.android.dev:id/product_sizes_text_view"]'
    COMPOSITIONS_AND_CARE = '//*[@resource-id="ru.limeshop.android.dev:id/productCompositionAndCareTextView"]'
    DELIVERY = '//*[@resource-id="ru.limeshop.android.dev:id/productDeliveryTextView"]'
    PRODUCT_STOCKS = '//*[@resource-id="ru.limeshop.android.dev:id/productStocksTextView"]'
    PAYMENT = '//*[@resource-id="ru.limeshop.android.dev:id/productPaymentTextView"]'
    GOES_WELL = '//*[@resource-id="ru.limeshop.android.dev:id/goesWellTextView"]'
    YOU_LIKE_IT = '//*[@resource-id="ru.limeshop.android.dev:id/youllLikeItTextView"]'
    GOES_WELL_SELECTOR_1 = '//*[@resource-id="ru.limeshop.android.dev:id/goesWellRecyclerView"]/android.widget.LinearLayout[1]'
    GOES_WELL_SELECTOR_2 = '//*[@resource-id="ru.limeshop.android.dev:id/goesWellRecyclerView"]/android.widget.LinearLayout[2]'
    YOU_LIKE_IT_SELECTOR_1 = '//*[@resource-id="ru.limeshop.android.dev:id/youllLikeItRecyclerView"]/android.widget.LinearLayout[1]'
    YOU_LIKE_IT_SELECTOR_2 = '//*[@resource-id="ru.limeshop.android.dev:id/youllLikeItRecyclerView"]/android.widget.LinearLayout[2]'
    # BOTTOM_SHEET
    XS_SIZE = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[1]'
    S_SIZE = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[2]'
    M_SIZE = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[3]'
    L_SIZE = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[4]'
    XL_SIZE = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[5]'
    SIZE_34 = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[1]'
    SIZE_36 = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[2]'
    SIZE_38 = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[3]'
    SIZE_40 = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[4]'
    SIZE_42 = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[5]'
    SIZE_44 = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]/android.view.ViewGroup[6]'
    SIZE_INFO = '//*[@resource-id="ru.limeshop.android.dev:id/sizeInfoButton"]'
    POPUP = '//*[@resource-id="ru.limeshop.android.dev:id/productPopup"]'
    POPUP_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/popupStartTitle"]'
    POPUP_BUTTON = '//*[@resource-id="ru.limeshop.android.dev:id/popupButton"]'
    product_size_list = d(resourceId="ru.limeshop.android.dev:id/product_add_to_cart_name")
    available_size = '//*[@resource-id="ru.limeshop.android.dev:id/sizeList"]//android.widget.TextView[@resource-id="ru.limeshop.android.dev:id/product_add_to_cart_name" and not(following-sibling::android.widget.TextView[@resource-id="ru.limeshop.android.dev:id/product_add_to_cart_available"])]'
    product_price = 'ru.limeshop.android.dev:id/productPriceTextView'
    product_name = 'ru.limeshop.android.dev:id/productNameTextView'


class ProfileLocators:
    # PROFILE
    PROFILE_ESTIMATION_TITLE = '//*[@text="ОЦЕНИТЕ ПРИЛОЖЕНИЕ:"]'
    PROFILE_ESTIMATION = '//android.widget.ScrollView/android.widget.LinearLayout[1]/androidx.appcompat.widget.LinearLayoutCompat[2]/androidx.appcompat.widget.LinearLayoutCompat[1]/android.widget.ImageView[5]'
    PRIVACY_POLICY = '// *[ @ text = "Политика конфиденциальности"]'
    TERMS_OF_PURCHASE = '// *[ @ text = "Условия покупки"]'
    FEATURE_TOGGLES = '//*[@resource-id="ru.limeshop.android.dev:id/profile_feature_toggle"]'
    VERSION_TEXT = '//*[@text="ВЕРСИЯ 3.23.6"]'
    app_id = 'ru.limeshop.android.dev:id/uuid_text_view'

    # PROFILE_UNAUTHORIZED
    MANUAL_UN = 'ru.limeshop.android.dev:id/profile_unauthorized_manual'
    CONTACTS_UN = 'ru.limeshop.android.dev:id/profile_unauthorized_contacts'
    COMPANY_UN = 'ru.limeshop.android.dev:id/profile_unauthorized_company'
    SHOPS_UN = 'ru.limeshop.android.dev:id/profile_unauthorized_shops'
    SUBSCRIPTIONS_UN = 'ru.limeshop.android.dev:id/profile_unauthorized_subscriptions'
    FEATURE_TOGGLES_UN = '//*[@resource-id="ru.limeshop.android.dev:id/profile_feature_toggle_unauthorized"]'
    CHAT_UN = '//*[@text="ЧАТ"]'
    LOGIN_UN = 'ru.limeshop.android.dev:id/profile_unauthorized_login'
    SIGNUP_UN = 'ru.limeshop.android.dev:id/profile_unauthorized_signup'
    phone_number = 'ru.limeshop.android.dev:id/textView42'
    dialer_digits = '//*[@resource-id="com.android.dialer:id/digits"]'

    # PROFILE_AUTHORIZED
    USERNAME = 'ru.limeshop.android.dev:id/nameTextView'
    EMAIL = 'ru.limeshop.android.dev:id/emailTextView'
    ORDERS = 'ru.limeshop.android.dev:id/profile_authorized_orders'
    MY_INFO = 'ru.limeshop.android.dev:id/profile_authorized_my_info'
    MANUAL = 'ru.limeshop.android.dev:id/profile_authorized_manual'
    CONTACTS = 'ru.limeshop.android.dev:id/profile_authorized_contacts'
    COMPANY = 'ru.limeshop.android.dev:id/profile_authorized_company'
    SHOPS = 'ru.limeshop.android.dev:id/profile_authorized_shops'
    SUBSCRIPTIONS = 'ru.limeshop.android.dev:id/profile_authorized_subscriptions'
    LOGOUT = 'ru.limeshop.android.dev:id/profile_authorized_logout'
    DELETE_ACCOUNT = 'ru.limeshop.android.dev:id/deleteAccountTextView'
    add_new_address_btn = 'ru.limeshop.android.dev:id/my_info_new_address'
    city = '//*[@resource-id="ru.limeshop.android.dev:id/info_city"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    street = '//*[@resource-id="ru.limeshop.android.dev:id/info_street"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    apartment = '//*[@resource-id="ru.limeshop.android.dev:id/info_apartment"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    postcode = '//*[@resource-id="ru.limeshop.android.dev:id/info_postcode"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    address_popup = 'ru.limeshop.android.dev:id/popUpRecycler'
    save_address_btn = 'ru.limeshop.android.dev:id/save_address_button'


class FeatureTogglesLocators:
    SWITCH_1 = '//*[@resource-id="ru.limeshop.android.dev:id/toggleRecycler"]/android.view.ViewGroup[1]/android.widget.Switch[1]'
    SWITCH_2 = '//*[@resource-id="ru.limeshop.android.dev:id/toggleRecycler"]/android.view.ViewGroup[2]/android.widget.Switch[1]'
    SWITCH_3 = '//*[@resource-id="ru.limeshop.android.dev:id/toggleRecycler"]/android.view.ViewGroup[3]/android.widget.Switch[1]'
    SWITCH_4 = '//*[@resource-id="ru.limeshop.android.dev:id/toggleRecycler"]/android.view.ViewGroup[4]/android.widget.Switch[1]'
    SWITCH_5 = '//*[@resource-id="ru.limeshop.android.dev:id/toggleRecycler"]/android.view.ViewGroup[5]/android.widget.Switch[1]'


class LoginLocators:
    # LOGIN_SCREEN
    LOGIN_SCREEN_TITLE = 'ru.limeshop.android.dev:id/orderflow_signin_title'
    LOGIN_SCREEN_HINT_EMAIL = 'ru.limeshop.android.dev:id/hintText, text="Эл. почта"'
    LOGIN_SCREEN_EMAIL = 'ru.limeshop.android.dev:id/signin_email'
    LOGIN_SCREEN_HINT_PASS = '"ru.limeshop.android.dev:id/hintText", text="Пароль"'
    LOGIN_SCREEN_PASS = 'ru.limeshop.android.dev:id/signin_password'
    LOGIN_SCREEN_SHOW_PASS = 'ru.limeshop.android.dev:id/endIcon'
    LOGIN_SCREEN_PASS_RESET = 'ru.limeshop.android.dev:id/signin_password_reset'
    LOGIN_SCREEN_SIGNIN = 'ru.limeshop.android.dev:id/signin_proceed'

    # REG_SCREEN
    SIGNUP_HINT_NAME = '"ru.limeshop.android.dev:id/hintText", text="Имя"'
    SIGNUP_NAME = '//*[@resource-id="ru.limeshop.android.dev:id/signup_name"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    SIGNUP_HINT_SURNAME = '"ru.limeshop.android.dev:id/hintText", text="Фамилия"'
    SIGNUP_SURNAME = '//*[@resource-id="ru.limeshop.android.dev:id/signup_lastname"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    SIGNUP_PHONE = '//*[@resource-id="ru.limeshop.android.dev:id/signup_phone"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    SIGNUP_HINT_PHONE = '"ru.limeshop.android.dev:id/hintText", text="Моб. телефон"'
    SIGNUP_EMAIL = '//*[@resource-id="ru.limeshop.android.dev:id/signup_email"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    SIGNUP_HINT_EMAIL = 'ru.limeshop.android.dev:id/hintText, text="Эл. почта"'
    SIGNUP_PASSWORD = '//*[@resource-id="ru.limeshop.android.dev:id/signup_password"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    SIGNUP_HINT_PASSWORD = '"ru.limeshop.android.dev:id/hintText", text="Пароль"'
    SIGNUP_REPEAT_PASSWORD = '//*[@resource-id="ru.limeshop.android.dev:id/signup_password_confirm"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    SIGNUP_HINT_REPEAT_PASSWORD = '"ru.limeshop.android.dev:id/hintText", text="Повтор нового пароля"'
    SIGNUP_SHOW_PASSWORD = '//*[@resource-id="ru.limeshop.android.dev:id/signup_password"]/android.view.ViewGroup[1]/android.widget.ImageView[1]'
    SIGNUP_SHOW_REPEAT_PASSWORD = '//*[@resource-id="ru.limeshop.android.dev:id/signup_password_confirm"]/android.view.ViewGroup[1]/android.widget.ImageView[1]'
    SIGNUP_SUBSCRIBE_TITLE = '//*[@text="Подписаться на новостную рассылку:"]'
    SIGNUP_SUBSCRIBE_WOMEN = '//*[@resource-id="ru.limeshop.android.dev:id/subscriptionRecycler"]/android.widget.LinearLayout[1]/android.widget.ImageView[1]'
    SIGNUP_SUBSCRIBE_MEN = '//*[@resource-id="ru.limeshop.android.dev:id/subscriptionRecycler"]/android.widget.LinearLayout[2]/android.widget.ImageView[1]'
    SIGNUP_SUBSCRIBE_KIDS = '//*[@resource-id="ru.limeshop.android.dev:id/subscriptionRecycler"]/android.widget.LinearLayout[3]/android.widget.ImageView[1]'
    SIGNUP_SUBSCRIBE_WOMEN_LABEL = '"ru.limeshop.android.dev:id/item_checkable_option_name", text="Женщины"'
    SIGNUP_SUBSCRIBE_MEN_LABEL = '"ru.limeshop.android.dev:id/item_checkable_option_name", text="Мужчины"'
    SIGNUP_SUBSCRIBE_KIDS_LABEL = '"ru.limeshop.android.dev:id/item_checkable_option_name", text="Дети"'
    SIGNUP_TERMS_TEXT = "ru.limeshop.android.dev:id/signup_terms_text_view"
    SIGNUP_SUBSCRIBE_ACCEPT = '//*[@resource-id="ru.limeshop.android.dev:id/checkable_option_active"]'
    SIGNUP_RESUME_BTN = '//*[@text="ПРОДОЛЖИТЬ"]'
    profile_avatar = 'ru.limeshop.android.dev:id/avatarImageView'


class CartLocators:
    CLEAR_ALL = 'ru.limeshop.android.dev:id/toolbar_secondary_text_view'
    FAVORITE = '//*[@resource-id="ru.limeshop.android.dev:id/favorites_image_view"]'
    PRODUCT_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/item_cart_name"]'
    ART = '//*[@resource-id="ru.limeshop.android.dev:id/item_cart_code"]'
    SIZE = '//*[@resource-id="ru.limeshop.android.dev:id/item_cart_size"]'
    COLOR = '//*[@resource-id="ru.limeshop.android.dev:id/item_cart_color"]'
    PRICE_TOTAL = '//*[@resource-id="ru.limeshop.android.dev:id/item_cart_total_price"]'
    PRICE_SALE = '//*[@resource-id="ru.limeshop.android.dev:id/item_cart_price_sale"]'
    DELETE = '//*[@resource-id="ru.limeshop.android.dev:id/delete_image_view"]'
    MINUS = '//*[@resource-id="ru.limeshop.android.dev:id/minus_image_view"]'
    PLUS = '//*[@resource-id="ru.limeshop.android.dev:id/plus_image_view"]'
    QUANTITY = '//*[@resource-id="ru.limeshop.android.dev:id/quantity_text_view"]'
    QUANTITY_TEXT = '//*[@resource-id="ru.limeshop.android.dev:id/textView3"]'
    PROMO_CODE = '//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    PRICE_TEXT = '//*[@resource-id="ru.limeshop.android.dev:id/textView5"]'
    SUMMARY_QUANTITY = '//*[@resource-id="ru.limeshop.android.dev:id/textView2"]'
    SUMMARY_PRICE = '//*[@resource-id="ru.limeshop.android.dev:id/textView4"]'
    SUMMARY_TEXT = '//*[@resource-id="ru.limeshop.android.dev:id/textView11"]'
    CONTINUE = '//*[@resource-id="ru.limeshop.android.dev:id/cart_continue_button"]'
    # CLEAR CART
    ICON = '//androidx.appcompat.widget.LinearLayoutCompat/android.widget.ImageView[1]'
    DESCRIPTION_CLEAR = '//*[@text="ВАША КОРЗИНА ПУСТА"]'
    BUY_BUTTON = '//*[@resource-id="ru.limeshop.android.dev:id/cart_buy_button"]'
    # POPUP
    POPUP_CLEAR = '//*[@resource-id="ru.limeshop.android.dev:id/positive_button_outlined"]'
    POPUP_CANCEL = '//*[@resource-id="ru.limeshop.android.dev:id/negative_button"]'
    POPUP_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/title_text_view"]'
    POPUP_DESCRIPTION = '//*[@resource-id="ru.limeshop.android.dev:id/message_text_view"]'


class CheckOutLocators:
    DELIVERY_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_title_text"]'
    DELIVERY_SELECTOR_1 = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[1]/android.widget.FrameLayout[1]'
    DELIVERY_SELECTOR_2 = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[2]/android.widget.FrameLayout[1]'
    DELIVERY_SELECTOR_3 = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[3]/android.widget.FrameLayout[1]'
    DELIVERY_TEXT_CUR = '//*[@text="КУРЬЕРОМ"]'
    DELIVERY_TEXT_SELF = '//*[@text="САМОВЫВОЗ"]'
    DELIVERY_PRICE_1 = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[1]/android.widget.TextView[2]'
    DELIVERY_PRICE_2 = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[2]/android.widget.TextView[2]'
    ADDRESS = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_info_title_text"]'
    SELECTED_ADDRESS = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_courier_title_text"]'
    ADD_ADDRESS_BUTTON = '//*[@resource-id="ru.limeshop.android.dev:id/add_courier_address_button"]'
    EDIT_ADDRESS = '//*[@resource-id="ru.limeshop.android.dev:id/edit_courier_address_image"]'
    NAME = '//*[@resource-id="ru.limeshop.android.dev:id/delivery_info_subtitle_text"]'
    PAYMENT_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/payment_title_text"]'
    PAYMENT_SELECTOR_1 = '//*[@resource-id="ru.limeshop.android.dev:id/payment_selector_component"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[1]/android.widget.FrameLayout[1]'
    PAYMENT_SELECTOR_2 = '//*[@resource-id="ru.limeshop.android.dev:id/payment_selector_component"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[2]/android.widget.FrameLayout[1]'
    PAYMENT_SELECTOR_3 = '//*[@resource-id="ru.limeshop.android.dev:id/payment_selector_component"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[3]/android.widget.FrameLayout[1]'
    PAYMENT_SELECTOR_4 = '//*[@resource-id="ru.limeshop.android.dev:id/payment_selector_component"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[4]/android.widget.FrameLayout[1]'
    PAYMENT_TITLE_1 = '//*[@text="ЧЕРЕЗ СБП"]'
    PAYMENT_TITLE_2 = '//*[@text="КАРТОЙ ОНЛАЙН"]'
    PAYMENT_TITLE_3 = '//*[@text="ПОДАРОЧНОЙ КАРТОЙ"]'
    PAYMENT_TITLE_4 = '//*[@text="ПРИ ПОЛУЧЕНИИ"]'
    PAYMENT_INFO_TEXT = '//*[@resource-id="ru.limeshop.android.dev:id/payment_info_title_text"]'
    SLOTS_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/time_slots_title_text"]'
    SLOTS_DATE_SELECTOR_1 = '//*[@resource-id="ru.limeshop.android.dev:id/date_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]'
    SLOTS_DATE_SELECTOR_2 = '//*[@resource-id="ru.limeshop.android.dev:id/date_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.FrameLayout[2]/android.widget.LinearLayout[1]'
    SLOTS_DATE_SELECTOR_3 = '//*[@resource-id="ru.limeshop.android.dev:id/date_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.FrameLayout[3]/android.widget.LinearLayout[1]'
    SLOTS_TIME_SELECTOR_1 = '//*[@resource-id="ru.limeshop.android.dev:id/time_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.FrameLayout[1]'
    SLOTS_TIME_SELECTOR_2 = '//*[@resource-id="ru.limeshop.android.dev:id/time_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.FrameLayout[2]'
    SLOTS_TIME_SELECTOR_3 = '//*[@resource-id="ru.limeshop.android.dev:id/time_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.FrameLayout[3]'
    SLOTS_TIME_SELECTOR_4 = '//*[@resource-id="ru.limeshop.android.dev:id/time_selector_view"]/android.widget.FrameLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.FrameLayout[4]'
    ORDER_LIST_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/order_list_title_text"]'
    ORDER_LIST_SHEVRON = '//*[@resource-id="ru.limeshop.android.dev:id/order_list_chevron_image"]'
    SUMMARY_QUANTITY_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/checkout_summary_quantity_title_text"]'
    SUMMARY_QUANTITY = '//*[@resource-id="ru.limeshop.android.dev:id/checkout_summary_quantity_text"]'
    SUMMARY_COAST_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/checkout_summary_cost_title_text"]'
    SUMMARY_COAST = '//*[@resource-id="ru.limeshop.android.dev:id/checkout_summary_cost_text"]'
    SUMMARY_TOTAL_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/checkout_summary_total_title_text"]'
    SUMMARY_TOTAL = '//*[@resource-id="ru.limeshop.android.dev:id/checkout_summary_total_text"]'
    ORDER_PAY = '//*[@resource-id="ru.limeshop.android.dev:id/order_pay_button"]'
    TERMS_TEXT = '//*[@resource-id="ru.limeshop.android.dev:id/checkout_terms_text"]'
    POPUP_BACK_CART_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/title_text_view"]'
    POPUP_BACK_CART_DESCRIPTION = '//*[@resource-id="ru.limeshop.android.dev:id/message_text_view"]'
    POPUP_BACK_CART_CANCEL = '//*[@resource-id="ru.limeshop.android.dev:id/positive_button"]'
    POPUP_BACK_CART_YES = '//*[@resource-id="ru.limeshop.android.dev:id/negative_button"]'
    ADD_NEW_CARD_PLUS = 'ru.limeshop.android.dev:id/add_payment_button'
    # Card online
    CARD_ICON = '//*[@resource-id="ru.limeshop.android.dev:id/payment_card_image"]'
    CARD_INFO = '//*[@resource-id="ru.limeshop.android.dev:id/payment_card_number_text"]'
    CARD_EDIT = '//*[@resource-id="ru.limeshop.android.dev:id/edit_payment_card_image"]'
    # BOTTOM-SHEET YOUR CARDS
    CARD_LIST_TITLE = '//*[@text="ВАШИ КАРТЫ"]'
    CARD_SELECTOR_1 = '//*[@resource-id="ru.limeshop.android.dev:id/is_selected_card_radio"]'
    CARD_ICON_BOTTOM_SHEET = '//*[@resource-id="ru.limeshop.android.dev:id/icon_image_view"]'
    CARD_INFO_BOTTOM_SHEET = '//*[@resource-id="ru.limeshop.android.dev:id/info_text_view"]'
    CARD_DELETE_SOLO = '//*[@resource-id="ru.limeshop.android.dev:id/delete_image_view"]'
    CARD_DELETE_1 = '//*[@resource-id="ru.limeshop.android.dev:id/saved_cards_recycler_view"]/android.view.ViewGroup[1]/android.widget.ImageView[2]'
    CARD_DELETE_2 = '//*[@resource-id="ru.limeshop.android.dev:id/saved_cards_recycler_view"]/android.view.ViewGroup[2]/android.widget.ImageView[2]'
    ADD_NEW_CARD_BUTTON = '//*[@resource-id="ru.limeshop.android.dev:id/add_new_card_button"]'
    # BOTTOM-SHEET ADD CARD
    ADD_CARD_TITLE = '//*[@text="ДОБАВИТЬ КАРТУ"]'
    ADD_CARD_NUMBER = '//*[@resource-id="ru.limeshop.android.dev:id/card_number"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    ADD_CARD_OWNER = '//*[@resource-id="ru.limeshop.android.dev:id/card_owner"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    ADD_CARD_EXPIRY = '//*[@resource-id="ru.limeshop.android.dev:id/card_expiry"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    ADD_CARD_CVV = '//*[@resource-id="ru.limeshop.android.dev:id/card_security"]/android.view.ViewGroup[1]/android.widget.EditText[1]'
    ADD_CARD_SAVE_CHECK_BOX = '//*[@resource-id="ru.limeshop.android.dev:id/saveCardCheckBox"]'
    ADD_CARD_SAVE_BUTTON = '//*[@resource-id="ru.limeshop.android.dev:id/order_continue_button"]'
    # POP-UP DELETE CARD
    DEL_CARD_POP_UP_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/title_text_view"]'
    DEL_CARD_POP_UP_DESCRIPTION = '//*[@resource-id="ru.limeshop.android.dev:id/message_text_view"]'
    DEL_CARD_POP_UP_DELETE = '//*[@resource-id="ru.limeshop.android.dev:id/danger_button"]'
    DEL_CARD_POP_UP_CANCEL = '//*[@resource-id="ru.limeshop.android.dev:id/negative_button"]'
    # ADD ADDRESS BOTTOM-SHEET
    ADD_ADDRESS_TITLE = '//*[@resource-id="ru.limeshop.android.dev:id/title_text"]'
    ADD_ADDRESS_CITY = '//*[@text="Город / Населенный пункт"]'
    ADD_ADDRESS_POPUP = '//*[@resource-id="ru.limeshop.android.dev:id/popupTextView"]'
    ADD_ADDRESS_STREET = '//*[@text="Улица и дом"]'
    ADD_ADDRESS_APARTMENT = '//*[@text="Квартира"]'
    ADD_ADDRESS_SAVE_BUTTON = '//*[@text="СОХРАНИТЬ"]'
    date = '//*[@resource-id="ru.limeshop.android.dev:id/date_selector_view"]//*[@resource-id="ru.limeshop.android.dev:id/text_container_layout"]'
    time = '//*[@resource-id="ru.limeshop.android.dev:id/time_selector_view"]//*[@resource-id="ru.limeshop.android.dev:id/selector_card"]'
    gift_card_selector = '//*[@text="ПОДАРОЧНОЙ КАРТОЙ"]/..'
    add_gift_card_title = d(resourceId="ru.limeshop.android.dev:id/title_view", text="ДОБАВИТЬ ПОДАРОЧНУЮ КАРТУ")
    gift_card_number_field = '//*[@resource-id="ru.limeshop.android.dev:id/number_text_input_edit"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    gift_card_sum_field = '//*[@resource-id="ru.limeshop.android.dev:id/amount_text_input_edit"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    gift_card_pin_field = '//*[@resource-id="ru.limeshop.android.dev:id/pin_text_input_edit"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    gift_card_balance = 'ru.limeshop.android.dev:id/errorText'
    gift_card_continue_btn = '//*[@text="ПРОДОЛЖИТЬ"]'
    pickup_selector = '//*[@text="САМОВЫВОЗ"]/..'
    courier_selector = '//*[@text="КУРЬЕРОМ"]/..'
    receiving_selector = '//*[@text="ПРИ ПОЛУЧЕНИИ"]/..'
    upon_receipt_text = d(resourceId="ru.limeshop.android.dev:id/payment_info_title_text", text='НАЛИЧНЫМИ ИЛИ КАРТОЙ ПРИ ПОЛУЧЕНИИ')
    permission_while_using_the_app = 'com.android.permissioncontroller:id/permission_allow_foreground_only_button'
    gift_number_text = '//*[@resource-id="ru.limeshop.android.dev:id/payment_gift_number_text"]'
    gift_card_dragger_view = 'ru.limeshop.android.dev:id/dragger_view'
    add_payment_btn = 'ru.limeshop.android.dev:id/add_payment_button'
    add_gift_card_btn = 'ru.limeshop.android.dev:id/add_payment_gift_button'
    gift_card_error = 'ru.limeshop.android.dev:id/errorText'
    payment_add_card_btn = 'ru.limeshop.android.dev:id/payment_add_card_text'
    payment_add_card_selector = 'ru.limeshop.android.dev:id/is_selected_card_radio'
    card_number = '//*[@resource-id="ru.limeshop.android.dev:id/card_number"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    cardholder = '//*[@resource-id="ru.limeshop.android.dev:id/card_owner"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    card_date = '//*[@resource-id="ru.limeshop.android.dev:id/card_expiry"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    card_cvv = '//*[@resource-id="ru.limeshop.android.dev:id/card_security"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    save_card_btn = 'ru.limeshop.android.dev:id/order_continue_button'
    cloud_payments = 'com.android.systemui:id/navigation_bar_frame'
    add_courier_address_btn = 'ru.limeshop.android.dev:id/add_courier_address_button'
    city = '//*[@resource-id="ru.limeshop.android.dev:id/edit_city"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    street = '//*[@resource-id="ru.limeshop.android.dev:id/edit_street"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    apartment = '//*[@resource-id="ru.limeshop.android.dev:id/edit_apartment"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    postcode = '//*[@resource-id="ru.limeshop.android.dev:id/edit_postcode"]//*[@resource-id="ru.limeshop.android.dev:id/editText"]'
    address_popup = 'ru.limeshop.android.dev:id/popUpRecycler'
    save_address_btn = '//*[@text="СОХРАНИТЬ"]'

class SuccessPayScreenLocators:
    ICON = '//*[@resource-id="ru.limeshop.android.dev:id/status_icon_image"]'
    TITLE = 'ru.limeshop.android.dev:id/status_title_text'
    DESCRIPTION = '//*[@text="Отслеживать его статус вы можете в личном кабинете"]'
    BUTTON = 'ru.limeshop.android.dev:id/action_button'
